version: '3.8'

services:
  app:
    build: .
    ports:
      - "8501:8501"
    environment:
      - STREAMLIT_SERVER_PORT=8501
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
    volumes:
      - .:/app

#  db:
#    image: mysql:8.0
#    ports:
#      - "3307:3306"
#    environment:
#      MYSQL_ROOT_PASSWORD: lighthousepgpw
#      MYSQL_DATABASE: lighthouse
#    volumes:
#      - mysql_data:/var/lib/mysql
#
#volumes:
#  mysql_data: