services:
  app:
    image: ghcr.io/itsnewe/ct-lighthouse-lite:master
    # Ports will be handled by Traefik
    # ports:
    #   - "8501:8501"
    expose:
      - "8501"
    environment:
      - STREAMLIT_SERVER_PORT=8501
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
    volumes:
      - lighthouse-static:/app/static
    networks:
      - ${DEPLOYMENT_NETWORKNAME}
    labels:
      - traefik.enable=true
      - traefik.http.routers.lighthouse.rule=Host(${TRAEFIK_HOST}) && PathPrefix(${TRAEFIK_PATHPREFIX})
      - traefik.http.routers.lighthouse.entrypoints=websecure
      - traefik.http.routers.tinyauth.tls.certresolver=letsencrypt
      - traefik.http.routers.tinyauth.tls=true
      - traefik.http.routers.lighthouse.priority=10
      - traefik.http.middlewares.lighthouse-stripprefix.stripprefix.prefixes=/lighthouse
      - traefik.http.routers.lighthouse.middlewares=lighthouse-stripprefix
      - traefik.http.services.lighthouse.loadbalancer.server.port=8501

volumes:
  lighthouse-static:
    external: true

networks:
 tinyauth_traefikarcanet:
    external: true
